language: ruby
cache: bundler
rvm:
  - 2.4.0
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token:
      secure: kYKtITZUByO0R0dsnlcJ1sOJsIyYWCHGdpleV8plY/sWj6aM7oiiQ6J3kcGBIV1zSWxVa919Uf+ygAaiXLDbqY8WijdxzXC47uExCTgOmODJ6Znr5BMduZnJTMdoaF5Vu6mfAqgj7gVWVbrdl7B8MpIpka7dXYABOepFxC5Ts9B4/Xt1DmE2lC6OjJ9UmFvggSwefrTFe4TU+BRljniGHApicIn2wpcK6Uc7F0U91NiZqIWgJjDH5EskZoIlV/+IIfzdOJjA+eeHiBjAeJ19dLrIqmG/5CLPgi1ujxDvoj+1NM5IJq93WKHnEf/rxYC7zKFhNYarh20cZ8P8QrChaYRLP5pnO9tx3ZURV4uH1eEvKijA/wYKi4+gyVlJClGioXfGsmznpXFjKKOmYHLOSG4HCAiu4Pvw1QaeuJq7gIuHNyZeslsIP81Q/7ogy17oREPLAfBsT8tz9c+ZdNY+xiRAuHEsQ3tAUPb+3VCK2twB/UEd5yAt6vBYLm93KIq6q370s6Wic7TNA5U/Yd3UPzy/YdwvkryMvDVnQr/d45qgiNG93T4DaSiG5768hBXF6rWNC7thM55Zrwz2UzO8JF5yrD7Y0DuZUe5Qavp9o9jBuVic5hQTkD8dqnTqCtJOsQoOD9HPWQc0+BGuGpkudW21uoLL1nuvawjEg+4AM3E=
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  slack:
    secure: Wpxa9QmYScZWoFxMiZYsc6qk5XnFFNq2lntGNLqc7JfJcK3eMW7dlhAW15r+N45EuqREnUucyFs2P/WtnVsYUflfFm0njxfBB7VNNlZA7Y/AzHvD1GbAyonDRIu1RMsXofBK7BIDdn73DXSkVS6PMoww4e9pIGZx0YmrRfQSlhIxYP38fB/aEHe6qAEcP8IAf31io8pGkbZsBiRBZ98LXlQvlICGYxo4BSuowOvXo2lLp0/D/JqoLJ8OCNlBF5V7U1G8BOoYvfd4bwXfD7I3fmVheKpoTBas04fe6iPINVbJLkYG/rq60TcDZrR88eEBbGN0A/bRJjvDm4pLWK75slvVI8KfHymaUVxkpUFqOa+nyALQWVf486oZPXh9M5vm+ecUY+gUFIUjtjNiZD7/buj0fJY/Rh+Ndm5qJ8NAPSaevn/cEqgj03wgeHz6/bD9CPpufi+rV1Nuc+CPRhFORg5CMkX6apFXFfH4j+2SoEgytDY4cQ+HiE+BuZ6IkyvynsJkK5amIfFo0EgG52B0jsvgnoWBBJHQCiTm0FwOLO/Dw7yGKG8945aR33gsSQl+uMO2IX6OAnoG9kHS4nRS5NKSSEH+FjJfcbXZlxnp7k3ZnTcDrJxcsr6z9TREwt+rpYCK/eY7fiqXB2vtY4PgyUm+i/6Y+yj2DTv9y1UI27s=
